
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mssqlnodejs 
spec:
  selector:
    matchLabels:
      app: mssqlnodejs 
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: mssqlnodejs 
    spec:
      containers:
      - name: mssqlnodejs 
        image: alisonjiang/mssqlnodejs
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "DMC_Bootcamp123"
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 1433
          protocol: TCP