
apiVersion: v1
kind: Service
metadata:
  name: mssqlnodejs-service 
  labels:
    app: mssqlnodejs-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: mssqlnodejs 