apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: pass-ext-params-api
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - accessStrategies:
        - config: {}
          handler: noop
      methods:
        - POST
      path: /.*
  service:
    host: pass-ext-params
    name: pass-ext-params
    port: 80
